# Generated by Django 4.2 on 2025-08-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='organization',
        ),
    ]
