# Generated by Django 4.2 on 2025-08-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('CSO', 'CSO'), ('CREDIT', 'Credit'), ('IT', 'IT'), ('OTHERS', 'Others')], max_length=50),
        ),
    ]
