# Generated by Django 4.2 on 2025-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('mandateCode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=255)),
                ('productId', models.IntegerField()),
                ('accountNumber', models.CharField(max_length=10)),
                ('accountName', models.CharField(max_length=255)),
                ('payerName', models.CharField(max_length=255)),
                ('payerEmail', models.EmailField(max_length=255)),
                ('amount', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=11)),
                ('subscriberCode', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
