# Generated by Django 4.2 on 2025-08-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directdebit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='mandateCode',
            new_name='id',
        ),
    ]
