# Generated by Django 4.2 on 2025-08-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directdebit', '0002_rename_mandatecode_mandate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mandate',
            old_name='id',
            new_name='mandateCode',
        ),
    ]
